name: "🚩 Report a Mistake (e.g. Spelling, Grammar, Wrong Info)"
description: >
  Did you find an error in the list?
title: 'Report a Mistake: <issue>'
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Before submitting, please read the **[Contribution Guidelines](https://github.com/awesome-obsidian/awesome-obsidian/blob/main/CONTRIBUTING.md)**.
        >
        > If you are familiar with GitHub and know how to create a Pull Request, please consider submitting your suggestion **directly as a PR** instead of opening an issue.

        **Thank you so much for your help to make this list even better! 💖**

  - type: textarea
    id: what-problem
    attributes:
      label: "What's the problem?"
      description: Briefly describe the error, or suggest a fix.
      placeholder: "wrote 'Obsidan' instead of 'Obsidian'"
    validations:
      required: true

  - type: input
    id: where-problem
    attributes:
      label: "Where's the problem?"
      description: Project name, category, or a link/line number pointing to the problem.
      placeholder: "ex. https://github.com/awesome-obsidian/awesome-obsidian/blob/main/README.md?plain=1#L20"
    validations:
      required: false
